// config/music.ts
import { Track } from "@/types/music";

export const INITIAL_TRACKS: Track[] = [
  {
    id: "1",
    title: "夏夜最后的烟火",
    artist: "颜人中",
    album: "My Summer",
    year: 2026,
    duration: "04:13",
    cover_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    external_url: "https://music.163.com",
    mood: ["chinese", "favorites", "night"],
    note: "深夜循环最多次的旋律，记录夏末的平静。",
  },
  {
    id: "2",
    title: "Ref:rain",
    artist: "Aimer",
    album: "daydream",
    year: 2026,
    duration: "04:48",
    cover_url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80",
    audio_url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    external_url: "https://music.163.com",
    mood: ["japanese", "night"],
    note: "雨天放空写代码时的首选。",
  },
  {
    id: "3",
    title: "Somewhere Only We Know",
    artist: "Keane",
    album: "Hopes and Fears",
    year: 2025,
    duration: "03:57",
    cover_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=80",
    external_url: "https://spotify.com",
    mood: ["favorites"],
    note: "关于时间、记忆与故地重游。",
  },
  {
    id: "4",
    title: "夜に駆ける",
    artist: "YOASOBI",
    album: "THE BOOK",
    year: 2024,
    duration: "04:21",
    cover_url: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80",
    external_url: "https://music.163.com",
    mood: ["japanese"],
  },
];